<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite time="684.75" tests="2" failures="0" errors="2" cancelled="0" hostname="Desktop" id="65656" name="Automated - UipathProject_TestAutomation_Tests - 1.0.67168848-alpha.7" package="UipathProject_TestAutomation_Tests_Tests-1.0.67168848-alpha.7" timestamp="2021-02-16T10:04:46.123Z">
    <testcase assertions="0" classname="UipathProject_TestAutomation_Tests" name="Tests\Application\Demo\Application Tests.xaml" status="Failed" time="643.54">
      <error message="A fault occurred while executing job 35265031 for Tests\Application\Demo\Application Tests.xaml. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65656/logs/35265031?fid=667126" type="Fault" />
      <system-out>Test case Tests\Application\Demo\Application Tests.xaml (v1.0.67168848-alpha.7) executed as job 35265031 and took 643540ms. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65656/logs/35265031?fid=667126</system-out>
    </testcase>
    <testcase assertions="0" classname="UipathProject_TestAutomation_Tests" name="Tests\RPA\RPA Tests.xaml" status="Failed" time="40.57">
      <error message="A fault occurred while executing job 35265032 for Tests\RPA\RPA Tests.xaml. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65656/logs/35265032?fid=667126" type="Fault" />
      <system-out>Test case Tests\RPA\RPA Tests.xaml (v1.0.67168848-alpha.7) executed as job 35265032 and took 40570ms. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65656/logs/35265032?fid=667126</system-out>
    </testcase>
  </testsuite>
</testsuites>