<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite time="150.953" tests="2" failures="0" errors="2" cancelled="0" hostname="Desktop" id="65425" name="Automated - UipathProject_TestAutomation_Tests - 1.0.66852393-alpha.7" package="UipathProject_TestAutomation_Tests_Tests-1.0.66852393-alpha.7" timestamp="2021-02-12T18:10:36.32Z">
    <testcase assertions="0" classname="UipathProject_TestAutomation_Tests" name="Tests\RPA\RPA Tests.xaml" status="Failed" time="111.123">
      <error message="A fault occurred while executing job 34737640 for Tests\RPA\RPA Tests.xaml. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65425/logs/34737640?fid=667126" type="Fault" />
      <system-out>Test case Tests\RPA\RPA Tests.xaml (v1.0.66852393-alpha.7) executed as job 34737640 and took 111123ms. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65425/logs/34737640?fid=667126</system-out>
    </testcase>
    <testcase assertions="0" classname="UipathProject_TestAutomation_Tests" name="Tests\Application\Demo\Application Tests.xaml" status="Failed" time="39.2">
      <error message="A fault occurred while executing job 34737641 for Tests\Application\Demo\Application Tests.xaml. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65425/logs/34737641?fid=667126" type="Fault" />
      <system-out>Test case Tests\Application\Demo\Application Tests.xaml (v1.0.66852393-alpha.7) executed as job 34737641 and took 39200ms. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65425/logs/34737641?fid=667126</system-out>
    </testcase>
  </testsuite>
</testsuites>