<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite time="699.603" tests="2" failures="1" errors="1" cancelled="0" hostname="Desktop" id="65577" name="Automated - UipathProject_TestAutomation_Tests - 1.0.67078167-alpha.7" package="UipathProject_TestAutomation_Tests_Tests-1.0.67078167-alpha.7" timestamp="2021-02-15T08:53:17Z">
    <testcase assertions="3" classname="UipathProject_TestAutomation_Tests" name="Tests\Application\Demo\Application Tests.xaml" status="Failed" time="685.113">
      <failure message="Verification failed." type="Failure" />
      <system-out>Test case Tests\Application\Demo\Application Tests.xaml (v1.0.67078167-alpha.7) executed as job 35122210 and took 685113ms. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65577/logs/35122210?fid=667126</system-out>
    </testcase>
    <testcase assertions="0" classname="UipathProject_TestAutomation_Tests" name="Tests\RPA\RPA Tests.xaml" status="Failed" time="13.85">
      <error message="A fault occurred while executing job 35122211 for Tests\RPA\RPA Tests.xaml. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65577/logs/35122211?fid=667126" type="Fault" />
      <system-out>Test case Tests\RPA\RPA Tests.xaml (v1.0.67078167-alpha.7) executed as job 35122211 and took 13850ms. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65577/logs/35122211?fid=667126</system-out>
    </testcase>
  </testsuite>
</testsuites>