<?xml version="1.0" encoding="utf-8"?>
<testsuites>
  <testsuite time="323.033" tests="2" failures="0" errors="1" cancelled="0" hostname="Desktop" id="65926" name="Automated - UipathProject_TestAutomation_Tests - 1.0.67430958-alpha.7" package="UipathProject_TestAutomation_Tests_Tests-1.0.67430958-alpha.7" timestamp="2021-02-19T10:52:57.15Z">
    <testcase assertions="0" classname="UipathProject_TestAutomation_Tests" name="Tests\Application\Demo\Application Tests.xaml" status="Failed" time="74.897">
      <error message="A fault occurred while executing job 35679113 for Tests\Application\Demo\Application Tests.xaml. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65926/logs/35679113?fid=667126" type="Fault" />
      <system-out>Test case Tests\Application\Demo\Application Tests.xaml (v1.0.67430958-alpha.7) executed as job 35679113 and took 74897ms. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65926/logs/35679113?fid=667126</system-out>
    </testcase>
    <testcase assertions="0" classname="UipathProject_TestAutomation_Tests" name="Tests\RPA\RPA Tests.xaml" status="Passed" time="246.263">
      <system-out>Test case Tests\RPA\RPA Tests.xaml (v1.0.67430958-alpha.7) executed as job 35679114 and took 246263ms. Logs are available at https://cloud.uipath.com/testisltfbgw/TestingXpertsDefault/test/executions/65926/logs/35679114?fid=667126</system-out>
    </testcase>
  </testsuite>
</testsuites>